server:
  port: 7081

spring:
  application:
    name: biometric-algo

# Hazelcast配置
hazelcast:
  cluster:
    name: biometric-cluster
  port: 5702
  members: 192.168.57.100,192.168.57.225


# 人脸识别参数
face:
  recognition:
    threshold: 0.6  # 匹配阈值，相似度大于此值认为匹配成功
    topN: 10  # 返回前N个最匹配的结果

logging:
  level:
    com.biometric.algo: INFO
    com.hazelcast: WARN

